name: notes
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf

    #         style: italic
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/roboto/roboto_regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

